### ISSUE TITLE
LoadError: Unable to autoload constant Transaction::SystemAllocation

### ISSUE THREAD

**Issue by dan-mi-sun** [blockades/mmt#19]
So, 

When switching from `development` -> `feature/event_store_5th_iteration` the first time I did not first run `bundle exec rake db:drop`. Was getting some errors so I switched back to `development`

and now am getting the following stacktrace:

```
Switched to branch 'development'
Your branch is up-to-date with 'origin/development'.
host% git branch
* development
  feature/event_store_5th_iteration
host% bundle exec rake db:drop   
Dropped database 'MMT_development'
Dropped database 'MMT_test'
host% git checkout feature/event_store_5th_iteration
M	.gitignore
Switched to branch 'feature/event_store_5th_iteration'
Your branch is up-to-date with 'origin/feature/event_store_5th_iteration'.
host% bundle exec rake db:create                    
Created database 'MMT_development'
Created database 'MMT_test'
host% bundle exec rake db:migrate                   
rake aborted!
LoadError: Unable to autoload constant Transaction::SystemAllocation, expected /home/user/Projects/mmt/app/subscribers/transaction/system_allocation.rb to define it
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/home/user/Projects/mmt/config/initializers/wisper.rb:3:in `<top (required)>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/home/user/Projects/mmt/config/environment.rb:7:in `<top (required)>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/user/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
host% bundle exec rake setup:coins                  
rake aborted!
LoadError: Unable to autoload constant Transaction::SystemAllocation, expected /home/user/Projects/mmt/app/subscribers/transaction/system_allocation.rb to define it
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/home/user/Projects/mmt/config/initializers/wisper.rb:3:in `<top (required)>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/home/user/Projects/mmt/config/environment.rb:7:in `<top (required)>'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/user/Projects/mmt/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/user/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => setup:coins => environment
(See full trace by running task with --trace)
```

**Comment by KGibb8** [comment]
Really wierd, I don't get this problem at all. Its we can easily solve it however. Should be able to change the `wisper.rb` to the following and remove the namespace from the subscribers, or remove the namespace from the model:

```ruby
Wisper.subscribe(Subscribers::SystemAllocation.new, scope: ::Transaction::SystemAllocation)
Wisper.subscribe(Subscribers::SystemWithdrawl.new, scope: ::Transaction::SystemWithdrawl)
Wisper.subscribe(Subscribers::SystemDeposit.new, scope: ::Transaction::SystemDeposit)
Wisper.subscribe(Subscribers::SystemExchange.new, scope: ::Transaction::SystemExchange)

Wisper.subscribe(Subscribers::MemberAllocation.new, scope: ::Transaction::MemberAllocation)
Wisper.subscribe(Subscribers::MemberWithdrawl.new, scope: ::Transaction::MemberWithdrawl)
Wisper.subscribe(Subscribers::MemberDeposit.new, scope: ::Transaction::MemberDeposit)
Wisper.subscribe(Subscribers::MemberExchange.new, scope: ::Transaction::MemberExchange)
```

Open to suggestions as to what people would prefer.

**Comment by mathieuatnos** [comment]
Already tried this one and strangely it didn't work.

**Comment by KGibb8** [comment]
I wonder, is this a spring issue? `bundle exec spring stop`

**Comment by mathieuatnos** [comment]
done too :\

**Comment by KGibb8** [comment]
Okay.. I've just done this on a fresh virtual box and I'm not able to recreate this problem with the `feature/event_store_5th_iteration` branch as it currently stands.

**Comment by dan-mi-sun** [comment]
Okay, I deleted the repo, cloned it again and then ran the following 

1. `git checkout feature/event_store_5th_iteration`
2. `git pull`
3. `bundle exec rake db:drop`
4. `bundle exec rake db:create`
5. `bundle exec rake db:migrate`
6. `bundle exec rake setup`
7. `rails s`

Passwords for signing in can be found here: https://github.com/blockades/mmt/blob/development/lib/tasks/setup.rake
