### ISSUE TITLE
You must disable two factor authentication before setting up again

### ISSUE THREAD

**Issue by dan-mi-sun** [blockades/mmt#23]
When entering in 2FA as develop it says:

> You must disable two factor authentication before setting up again

Even after first setting it up.

```
app/interactors/setup_two_factor_authentication.rb:34:in `setup_by_phone'
app/interactors/setup_two_factor_authentication.rb:25:in `block in setup_by_method'
app/interactors/setup_two_factor_authentication.rb:11:in `block in call'
app/interactors/setup_two_factor_authentication.rb:7:in `call'
app/controllers/members/two_factor_controller.rb:20:in `create'
Started POST "/settings/two_factor_authentication" for 127.0.0.1 at 2017-11-19 10:06:22 +0000
Processing by Members::TwoFactorController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"aGzSB0XSRudCLwseTL/r4CxB9t5TTRr8whW/Bg8U5DNEe0ZtMRDXJRfDztYYOAjQJQIdBQjqCCUBOAlpXuxZvQ==", "two_factor"=>{"otp_delivery_method"=>"sms", "country_code"=>"61", "phone_number"=>"0401391695"}, "commit"=>"Setup"}
  Member Load (0.6ms)  SELECT  "members".* FROM "members" WHERE "members"."id" = $1 ORDER BY "members"."id" ASC LIMIT $2  [["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  Member Exists (0.4ms)  SELECT  1 AS one FROM "members" WHERE "members"."username" = $1 AND ("members"."id" != $2) LIMIT $3  [["username", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  Member Exists (0.3ms)  SELECT  1 AS one FROM "members" WHERE "members"."slug" = $1 AND ("members"."id" != $2) LIMIT $3  [["slug", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  Member Exists (0.3ms)  SELECT  1 AS one FROM "members" WHERE "members"."email" = $1 LIMIT $2  [["email", "develop"], ["LIMIT", 1]]
  CACHE Member Exists (0.0ms)  SELECT  1 AS one FROM "members" WHERE "members"."username" = $1 AND ("members"."id" != $2) LIMIT $3  [["username", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  CACHE Member Exists (0.0ms)  SELECT  1 AS one FROM "members" WHERE "members"."slug" = $1 AND ("members"."id" != $2) LIMIT $3  [["slug", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  CACHE Member Exists (0.0ms)  SELECT  1 AS one FROM "members" WHERE "members"."email" = $1 LIMIT $2  [["email", "develop"], ["LIMIT", 1]]
  SQL (0.4ms)  UPDATE "members" SET "country_code" = $1, "phone_number" = $2, "updated_at" = $3, "otp_recovery_codes" = $4 WHERE "members"."id" = $5  [["country_code", "61"], ["phone_number", "0401391695"], ["updated_at", "2017-11-19 10:06:24.433347"], ["otp_recovery_codes", "{394ac46f1859cc01,eb1ee62a50deb96f,553a3709700e6790,0ec43948cc1ad846,a2b176c0f51cd7f7,1f598a1c67f7d4a5,06d0c95866888ba5,4fd9a39805573dbd,4c5ce31733743ac3,d7a601ffd837d2d6,e7b7b2d31f6c9aa9,8512462c16c4261d,2120f135d3470dc1,21237aa4075e6d13,164eb718384c60d1,0b1fd9cf3ff9ee19,0925d6a0377b50f7,d7bd94e44d3a6575}"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"]]
  Member Exists (0.3ms)  SELECT  1 AS one FROM "members" WHERE "members"."username" = $1 AND ("members"."id" != $2) LIMIT $3  [["username", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  Member Exists (0.2ms)  SELECT  1 AS one FROM "members" WHERE "members"."slug" = $1 AND ("members"."id" != $2) LIMIT $3  [["slug", "develop"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  Member Exists (0.2ms)  SELECT  1 AS one FROM "members" WHERE "members"."email" = $1 LIMIT $2  [["email", "develop"], ["LIMIT", 1]]
  SQL (0.3ms)  UPDATE "members" SET "updated_at" = $1, "direct_otp" = $2, "direct_otp_sent_at" = $3 WHERE "members"."id" = $4  [["updated_at", "2017-11-19 10:06:24.437917"], ["direct_otp", "580435"], ["direct_otp_sent_at", "2017-11-19 10:06:24.434732"], ["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"]]
   (4.6ms)  COMMIT
Redirected to http://localhost:3000/settings/two_factor_authentication/confirm
Completed 302 Found in 2143ms (ActiveRecord: 9.1ms)


Started GET "/settings/two_factor_authentication/confirm" for 127.0.0.1 at 2017-11-19 10:06:24 +0000
Processing by Members::TwoFactorController#edit as HTML
  Member Load (0.5ms)  SELECT  "members".* FROM "members" WHERE "members"."id" = $1 ORDER BY "members"."id" ASC LIMIT $2  [["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
Redirected to http://localhost:3000/settings/two_factor_authentication
Filter chain halted as :return_to_index rendered or redirected
Completed 302 Found in 2ms (ActiveRecord: 0.5ms)


Started GET "/settings/two_factor_authentication" for 127.0.0.1 at 2017-11-19 10:06:24 +0000
Processing by Members::TwoFactorController#index as HTML
  Member Load (0.3ms)  SELECT  "members".* FROM "members" WHERE "members"."id" = $1 ORDER BY "members"."id" ASC LIMIT $2  [["id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
  Rendering members/two_factor/index.html.slim within layouts/application
  Rendered members/two_factor/index.html.slim within layouts/application (5.4ms)
  Portfolio Load (0.4ms)  SELECT  "portfolios".* FROM "portfolios" WHERE "portfolios"."member_id" = $1 AND "portfolios"."next_portfolio_id" IS NULL LIMIT $2  [["member_id", "afd38285-fcb2-4628-b0a6-29ed284e6d27"], ["LIMIT", 1]]
Completed 200 OK in 30ms (Views: 27.4ms | ActiveRecord: 0.7ms)
```

**Comment by KGibb8** [comment]
Can you please clarify what you think it should do and what it actually does?

**Comment by KGibb8** [comment]
And/or steps to recreate

**Comment by KGibb8** [comment]
I'm closing this as I'm not sure what the issue was an no-one has clarified.
