### ISSUE TITLE
Cannot db:migrate with Docker

### ISSUE THREAD

**Issue by ameba23** [blockades/mmt#29]
### Steps to reproduce

1.sudo docker build -t test/mmt-dockerfile . 
2. docker-compose up
(mmt fails at this point with 'switch to inspect mode'.  this i think is a trivial error, we cant still start it with docker now that postgres is running)
3. sudo docker run -i -t -e DATABASE_URL=hostnamehere test/mmt-dockerfile rake db:create
4. sudo docker run -i -t -e DATABASE_URL=hostnamehere test/mmt-dockerfile rake db:migrate

I might have missed something, but basically i managed to get db:create to succeed, meaning the mmt docker container is communicating with the postgres container

### Expected behavior

it succeeds.  

### Actual behavior
```
rake aborted!
Psych::BadAlias: Unknown alias: default
/usr/local/bundle/gems/railties-5.1.4/lib/rails/secrets.rb:27:in `block in parse'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `each'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `each_with_object'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `parse'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:391:in `secrets'
/usr/local/bundle/gems/devise-4.3.0/lib/devise/rails.rb:36:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/mmt/config/environment.rb:7:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```
### todo
also to do would be set up volumes.

**Comment by dan-mi-sun** [comment]
This is being worked on here: https://github.com/blockades/mmt/pull/30

**Comment by KGibb8** [comment]
This is resolved in latest docker PR https://github.com/blockades/mmt/pull/35
