### ISSUE TITLE
Event failing to find relevant transaction before save

### ISSUE THREAD

**Issue by KGibb8** [blockades/mmt#51]
### Steps to reproduce

1. Switch to spreadsheet_approach branch
2. Run tests OR try to create an allocation

### Expected behavior

Should create Liability event

### Actual behavior
Fails to find the relevant system transaction to complete validation, returns nil and bombs out.
```
mmt_1      | 
mmt_1      | From: /mmt/app/models/events/liability.rb @ line 16 Events::Liability#coin_assets:
mmt_1      | 
mmt_1      |     14: def coin_assets
mmt_1      |     15:   binding.pry
mmt_1      |  => 16:   assets = coin.assets + system_transaction.asset_events.to_a.sum(&:assets)
mmt_1      |     17:   liabilities = system_transaction.liability_events.to_a.sum(&:liability)
mmt_1      |     18:   assets_after = assets - liabilities.abs
mmt_1      |     19:   return true if assets_after.positive? || assets_after.zero?
mmt_1      |     20:   self.errors.add :assets, "Insufficient assets"
mmt_1      |     21: end
mmt_1      | 
[1] pry(#<Events::Liability>)>   CACHE  (0.1ms)  SELECT SUM("events"."entry") FROM "events" WHERE "events"."type" IN ('Asset') AND "events"."coin_id" = $1  [["coin_id", "e3efca19-55ee-414c-ad0f-d2eb5996aabe"]]
mmt_1      |    (1.4ms)  ROLLBACK
mmt_1      | Completed 500 Internal Server Error in 238ms (ActiveRecord: 15.4ms)
mmt_1      | 
mmt_1      | 
mmt_1      |   
mmt_1      | NoMethodError (undefined method `asset_events' for nil:NilClass):
mmt_1      |   
mmt_1      | app/models/events/liability.rb:16:in `coin_assets'
mmt_1      | app/helpers/transaction_helper.rb:10:in `block in transaction_commiter'
mmt_1      | app/helpers/transaction_helper.rb:9:in `transaction_commiter'
mmt_1      | app/controllers/admins/system_allocations_controller.rb:15:in `create'

```

**Comment by nikolai-b** [comment]
I'm just getting

```
RuntimeError:
  can't modify frozen Array
```

for all the specs....

**Comment by KGibb8** [comment]
Resolved. It was missing `inverse_of`

**Comment by nikolai-b** [comment]
yep, that is what I wanted to add.

**Comment by nikolai-b** [comment]
With polymorphic stuff you need to be explicit about it.  Any ideas why the specs give me that error?

**Comment by KGibb8** [comment]
I've been getting it when missing a comma in a has many...
